# Use Node.js version 20
FROM node:20-alpine

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY package.json pnpm-lock.yaml /app/

# Copy the rest of the app's code
COPY . /app

# Expose the port and start the app
EXPOSE 5173

CMD [ -d "node_modules" ] && pnpm dev --host || pnpm install && pnpm dev --host
