name: hkufoss-frontend
services:
  frontend:
    container_name: hkufoss-frontend
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development # Set environment variables
    # command: pnpm dev --host # Command to run your app
