name: hkufoss-booking-frontend
services:
  room-booking-frontend:
    container_name: hkufoss-booking-frontend
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - hkufoss
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_PROJECT_NAME=HKUFOSS Booking Admin Portal

    # command: pnpm dev --host # Command to run your app

networks:
  hkufoss:
    name: hkufoss
    external: true
