name: hkufoss-booking-frontend
services:
  room-booking-frontend:
    container_name: hkufoss-booking-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    # restart: unless-stopped
    networks:
      - hkufoss
    volumes:
      - .:/app

networks:
  hkufoss:
    name: hkufoss
    external: true
